### PR TITLE
Filter Datatype for Message, needed for yahoo

### PR DESCRIPTION
**Pull request by gtawelt**

### CODE REVIEW

**Comment by twrecked** [comment]
Thanks for working on this. It works with my Google and Apple accounts so I'll approve it.

Apologies for the delay getting to this.

**Comment by twrecked** [comment]
I'll take a look. What mail provider are you using?

**Comment by m0urs** [comment]
Thanks. I am using https://www.ionos.de/

**Comment by twrecked** [comment]
Thanks. I think I need to enhance the code to try both. Sorry for the inconvenience.

**Pull request merged**
